#!/usr/bin/python3

import sys
import math


def factorize(num):
    factors = []
    # Check for divisibility by 2
    while num % 2 == 0:
        factors.append(2)
        num //= 2

    # Check for divisibility by odd numbers up to the square root of num
    for i in range(3, int(math.sqrt(num)) + 1, 2):
        while num % i == 0:
            factors.append(i)
            num //= i

    # If num is still greater than 2, it must be prime
    if num > 2:
        factors.append(num)

    return factors


def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        print("where <file> is a file containing natural numbers to factor.")
        sys.exit(1)

    filename = sys.argv[1]

    with open(filename, 'r') as file:
        numbers = file.read().splitlines()

    for num in numbers:
        num = int(num)
        factors = factorize(num)
        print("{}={}".format(num, '*'.join(map(str, factors))))


if __name__ == '__main__':
    main()
